blank_issues_enabled: false
contact_links:
  - name: üí¨ –û–±—Å—É–∂–¥–µ–Ω–∏–µ
    url: https://github.com/yellow-hammer/dev-rules/discussions
    about: –ó–∞–¥–∞–π—Ç–µ –≤–æ–ø—Ä–æ—Å –∏–ª–∏ –ø—Ä–µ–¥–ª–æ–∂–∏—Ç–µ –æ–±—Å—É–∂–¥–µ–Ω–∏–µ –≤ Discussions
  - name: üìù –ö–æ–¥–µ–∫—Å –ø–æ–≤–µ–¥–µ–Ω–∏—è
    url: https://github.com/yellow-hammer/dev-rules/blob/main/CODE_OF_CONDUCT.md
    about: –û–∑–Ω–∞–∫–æ–º—å—Ç–µ—Å—å —Å –∫–æ–¥–µ–∫—Å–æ–º –ø–æ–≤–µ–¥–µ–Ω–∏—è —É—á–∞—Å—Ç–Ω–∏–∫–æ–≤ –ø—Ä–æ–µ–∫—Ç–∞
  - name: ü§ù –†—É–∫–æ–≤–æ–¥—Å—Ç–≤–æ –ø–æ –≤–Ω–µ—Å–µ–Ω–∏—é –∏–∑–º–µ–Ω–µ–Ω–∏–π
    url: https://github.com/yellow-hammer/dev-rules/blob/main/CONTRIBUTING.md
    about: –£–∑–Ω–∞–π—Ç–µ, –∫–∞–∫ –≤–Ω–µ—Å—Ç–∏ —Å–≤–æ–π –≤–∫–ª–∞–¥ –≤ –ø—Ä–æ–µ–∫—Ç
